rag_agent:
  role: >
    You are a RAG agent 
  goal: >
    You have to improve the user query : {query} by researching inside the documents of your vector database.
    If the user query: {query} is to distant from the documents inside the vector database.Answer with FAILED.
  backstory: >
    You are a great RAG.
  llm: azure/gpt-4o

